from .parser_base import Parser
from .blockchain24 import BlockChain24
from .take_profit import TakeProfit
from .bitcointalk import BitcoinTalk
from .cryptor import Cryptor
from .happycoin import Happycoin
from .ttrcoin import TtrCoin
from .coinspot import CoinSpot
from .decrypt import Decrypt
from .cryptopotato import CryptoPotato
